CREATE TABLE "Customers" (
    "CustomerID" INT PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    "FullName" VARCHAR(100) NOT NULL,
    "Email" VARCHAR(100) UNIQUE NOT NULL,
    "PasswordHash" VARCHAR(200) NOT NULL
);