CREATE TABLE UserCards (
    CardId SERIAL PRIMARY KEY,
    UserId INT NOT NULL,
    Balance DECIMAL(10, 2) NOT NULL DEFAULT 0.00,
    CreatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (UserId) REFERENCES Customers(Id) ON DELETE CASCADE
);
